### PR TITLE
Substitute $SRC in arguments

### PR DESCRIPTION
**Pull request by tchajed**
Replaced with full path to source directory for the application version.
Currently only arguments is substituted, but this change also creates the
infrastructure to provide substitution of any environment variable into many of
the other config keys (eg, the build command could use it).

A further followup would be to add a key for environment variables to modify
for the build or run, which would themselves have substitutions performed. This
feature is really only motivated by Go, where building requires that GOPATH be
set correctly somehow.

### CODE REVIEW

**Comment by tchajed** [comment]
Written on top of #8l, to avoid rebase issues.

**Comment by jonhoo** [comment]
See comments on tchajed/experiment#291634f76c8f8d096230044b7c011a3e82ff657a.
Also, these three commits do very different things. I'd prefer them as separate PRs if possible.

**Comment by tchajed** [comment]
History re-writing detached the comments from the pull request, but fixed the issues with tchajed/experiment@291634f with 38db124 and split off #11 and #12.

**Comment by jonhoo** [comment]
Thanks!

**Pull request merged**
